### ISSUE TITLE
Following instructions results in "no such app"

### ISSUE THREAD

**Issue by kylebragger** [dockhero/quic-protocol-demo#2]
I followed the instructions exactly for this demo and the resulting dockhero.io URL yields the "no such app" Heroku error page.

Steps to repro:
1.  heroku addons:create dockhero
2.  heroku plugins:install dockhero
3.  heroku dh:wait
4.  heroku dh:compose up -d
5.  heroku logs --tail -p dockhero
6.  heroku dh:open

dockhero-compose.yml:
```
version: "2"

services:
  proxy:
    image: dockhero/caddy-proxy
    restart: "on-failure:10"
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_certificates:/srv
    environment:
      VIRTUAL_HOSTS: https://${DOCKHERO_HOST}
      TARGET_URL: ${HEROKU_APP_URL}

volumes:
  caddy_certificates:
    driver: local
```

Everything is deployed and the app is otherwise accessible on Heroku.
